name: Build Arch Linux Installer Boot Part

# Controls when the workflow will run
on:
  push:
    tags:
      - 'b*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build Image for Edge 2 seperated boot partition
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/archlinux-installer) --kernel=linux-edge2 --sbc=edge2 --addpkg=ap6275p-firmware -c -b --image=archlinux-installer-edge2-sepboot.img
          mv out/*.img.xz *.img.xz
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "archlinux-installer-edge2-sepboot.img.xz"
            makeLatest: false
            prerelease: true
            allowUpdates: true
