name: Build Arch Linux Gnome Image

# Controls when the workflow will run
on:
  push:
    tags:
      - 'd*gnome'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-rock:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Extract U-Boot
        run: |
          curl -L https://github.com/radxa-repo/bullseye/raw/gh-pages/.pool/u-boot-rknext_2017.09-10-52701b7_arm64.deb -o uboot.deb
          ar xv uboot.deb
          tar -xf data.tar.xz
          ls -l

      - name: Build Image for Rock 5B
        run: |
          curl -LJO https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/scripts/bsp6-panthor-gnome-install.sh
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --sbc=rock5 --addpkg=linux-firmware-joshua-git -c --script=bsp6-panthor-gnome-install.sh --size=8G --image=rock-5b-archlinux-gnome.img --uboot=usr/lib/u-boot/rock-5b
          cp -r out/rock-5b-archlinux-gnome.img.xz rock-5b-archlinux-gnome.img.xz

      - uses: ncipollo/release-action@v1
        with:
            artifacts: "*-archlinux-gnome.img.xz"
            makeLatest: false
            prerelease: true
            allowUpdates: true
            omitBody: true

  build-edges:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Extract U-Boot
        run: |
          curl -L https://dl.khadas.com/repos/edge2/pool/main/l/linux-u-boot-edge2-vendor/linux-u-boot-edge2-vendor_1.6.5-2017.09_arm64.deb -o uboot.deb
          ar xv uboot.deb
          tar -xf data.tar.xz
          ls -l

      - name: Build Image for Edge 2
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/create-installation-media) --kernel=linux-rockchip-joshua-git --sbc=edge2 --addpkg=linux-firmware-joshua-git -c -b --script=bsp6-panthor-gnome-install.sh --size=8G --image=edge2-archlinux-gnome.img --uboot=usr/lib/u-boot
          cp -r out/edge2-archlinux-gnome.img.xz edge2-archlinux-gnome.img.xz

      - name: Add meta data to Image for Edge 2
        run: |
          bash <(curl -fsSL https://raw.githubusercontent.com/khadas/krescue/master/tools/xze) "edge2-archlinux-gnome.img.xz" \
             --meta \
             label="Arch Linux Gnome" \
             builder="Arch Linux Gnome" \
             date="$(LANG=C TZ= date)" \
             match=BOARD=Edge2 \
             link=https://github.com/kwankiu/archlinux-installer-rock5/wiki \
             duration=250 \
             desc="Community-built Arch Linux Gnome for ARM (Aarch64), Image built for Khadas Edge 2"
        continue-on-error: true

      - uses: ncipollo/release-action@v1
        with:
            artifacts: "*-archlinux-gnome.img.xz"
            makeLatest: false
            prerelease: true
            allowUpdates: true
            omitBody: true
