name: Build Arch Linux Installer for Rock 5

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build Image
        run: |
          uname -a
          lsblk
          sudo losetup -a
          bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/main/archlinux-installer) -d -i -k
      - name: Upload to Release Action
        uses: Shopify/upload-to-release@v1.0.1
        with:
          # Artifact name
          name: archlinux-installer-rock5.img
          # Path to the file to upload
          path: ${pwd}/out/
          # secrets.GITHUB_TOKEN
          repo-token: ${{ secrets.GITHUB_TOKEN }}