name: Build Arch Linux Installer for Rock 5 on AARCH64

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Mount current directory in the container
          dockerRunArgs: |
            --volume "${PWD}"

          run: |
            uname -a
            uname -m
            sudo apt update && sudo apt install curl
            bash <(curl -fsSL https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/dev/archlinux-installer) -i -k -c --disk=/dev/loop3
          
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "out/archlinux-installer-rock5.img.xz"
            prerelease: true
            allowUpdates: true
            tag: "alpha"