name: Release Boot Templates

# Controls when the workflow will run
on:
  push:
    tags:
      - 'kernel'
      - 'e*template'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build Rock 5B
        run: |
          echo $GITHUB_WORKSPACE
      - uses: ncipollo/release-action@v1
        with:
            artifacts: "WIP"
            makeLatest: false
            prerelease: false
            allowUpdates: true
